name: Generate Ascii code
'on': push
jobs:
  generate_cowsay:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install cowsay
        run: sudo apt-get install cowsay -y
      - name: Execute cowsay command
        run: cowsay -f dragon "Run for cover" >> dragon.txt
      - name: sleep 10 seconds
        run: sleep 10s
      # - name: Test if file exist
      #   run: grep i "dragon" dragon.txt
      - name: Read file
        run: cat dragon.txt
      - name: List files
        run: ls -ltra
